# Generated by Django 2.2.10 on 2021-05-16 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=1024)),
                ('note', models.CharField(max_length=1024)),
                ('contact', models.CharField(max_length=32)),
                ('card_type', models.CharField(default='3-Ply CardBoard Simple', max_length=64)),
                ('status', models.CharField(default='Pending', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
