# Generated by Django 2.2.10 on 2021-06-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orders',
            name='note',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
    ]
