# Generated by Django 2.2.10 on 2021-07-12 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_feedback_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feeback',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='feeback',
            new_name='feedback',
        ),
    ]
